global:
  scrape_interval: 15s

# Scrape configuration
scrape_configs:

  # Prometheus itself
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'localhost:9090' ]

  # Host machine
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'node_exporter:9100' ]

  # Docker containers
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'cadvisor:8080' ]

  # Nginx server
  - job_name: 'nginx_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'nginx_exporter:9113' ]
