route:
  group_by: [ 'alertname', 'cluster', 'service' ]
  group_wait: 1s
  group_interval: 1s
  repeat_interval: 4h
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
      - api_url: 'https://api.telegram.org'
        chat_id: -1001847065832
        bot_token_file: '/etc/alertmanager/_secrets/bot_token.txt'

templates:
  - '/etc/alertmanager/*.tmpl'
