global:
  scrape_interval: 15s

# Scrape configuration
scrape_configs:

  # Prometheus itself
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'localhost:9090' ]

  # General host metrics
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'vm20:9100', 'vm21:9100', 'vm23:9100' ]

  # Docker containers
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'vm20:8080', 'vm21:8080', 'vm23:8080' ]

  # Nginx server
  - job_name: 'nginx_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'vm21:9113' ]

  # Loki
  - job_name: 'loki'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'vm23:3100' ]
